---
- name: NXOS Example
  hosts: nxos
  tasks:
    - name: Configure interfaces
      nxos_l3_interface:
        provider: "{{ provider_ssh}}"
        name: "{{ item.name }}"
        ipv4: "{{ item.ipv4 }}"
        ipv6: "{{ item.ipv6 }}"
      with_items: "{{ ip_addrs }}"
      notify: write mem
  
  handlers:
    - name: write mem
      nxos_command:
        provider: "{{ provider_ssh }}"
        commands: copy run start
      changed_when: True
      tags: wr_mem
