---

- name: Generate configurations for IOS, NXOS and Arista switches
  hosts: cisco,nxos,arista
  tasks:
    - name: Generate config files 
      template:
        src: multi_config.j2
        dest: "./CFGS/{{ inventory_hostname }}.txt"

- name: Push IOS Config
  hosts: cisco
  tasks:
    - ios_config:
        provider: "{{ creds_core }}"
        src: "./CFGS/{{ inventory_hostname }}.txt"

- name: Push nxos Config
  hosts: nxos 
  tasks:
    - nxos_config:
        provider: "{{ creds_core }}"
        src: "./CFGS/{{ inventory_hostname }}.txt"

- name: Push arista Config
  hosts: arista 
  tasks:
    - eos_config:
        provider: "{{ creds_core }}"
        src: "./CFGS/{{ inventory_hostname }}.txt"
