---
- name: Show ARP
  hosts: cisco
  vars:
    creds:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}" 
      password: "{{ ansible_ssh_pass }}"
  
  tasks:
    - ios_command:
        provider: "{{ creds }}"
        commands: show arp
      register: show_arp

    - set_fact:
        show_arp_new: "{{ show_arp.stdout_lines[0] }}"

    - debug:
        var: show_arp_new
    
    - debug:
        msg: "{{ item }}"
      with_items: "{{ show_arp_new }}"
      when: "'10.220.88.1' in item"
