---
- name: Basic ios_facts module
  hosts: cisco
  vars:
    creds:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}" 
      password: "{{ ansible_ssh_pass }}"

  tasks:
    - name: Gather Facts
      ios_facts:
        provider: "{{ creds }}"
      tags: facts_only
  
    - name: Get serial numbers
      debug:
        msg: "{{ ansible_net_serialnum }}"    
