---
- name: Exercise 1a
  hosts: pynet-rtr1
  tasks:
    - name: Get LLDP info
      napalm_get_facts:
        provider: "{{ creds }}"
        filter: "lldp_neighbors"
    
    - set_fact:
        my_lldp: "{{ napalm_lldp_neighbors.FastEthernet4[0] }}"

    - name: Bonus where not hard-coding name (with_items will retrieve the key)
      set_fact:
        lldp_info_alt: "{{ napalm_lldp_neighbors[item][0] }}"
      with_items: "{{ napalm_lldp_neighbors }}"
 
    - assert:
        that: my_lldp.hostname == "twb-sf-hpsw1"
