---
- name: napalm_install_config merge configure ip example
  hosts: nxos
  tasks:
    - napalm_install_config:
        provider: "{{ creds }}"
        config_file: "CFGS/{{ inventory_hostname }}-merge.txt"
        commit_changes: False
        replace_config: False
        diff_file: "DIFFS/{{ inventory_hostname }}.txt"
